version: "3.9"
services:
#  Reward your teacher app
  app:
    container_name: teacher
    build: ./
    depends_on:
      - postgresqldb
    ports:
      - "5200:9001"
    env_file:
      - .env

#Postgres db
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    ports:
        - "4500:5432"
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres

#pg admin app
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:






