server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: false
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-authentication-method: post
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL}
            scope:
              - email
              - profile
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${GMAIL_USERNAME} #<Login User to SMTP server>
    password: ${GMAIL_SMTP_PASSWORD} #<Login password to SMTP server>
    port: '587'
springdoc:
  swagger-ui:
    path: /api-docs

jwt:
  adminKey:
    ${JWT_ADMIN_KEY}
cloudinary_name:
  wingsmarket
cloudinary_api_key:
  ${CLOUDINARY_API_KEY}
cloudinary_api_secret:
  ${CLOUDINARY_API_SECRET}
paystack_secret_key:
  ${PAYSTACK_SECRET_KEY}

#  sk_test_4a9cc5c7ac230a48c417031a52010a676f5cd394